version: '3.8'

services:
  audiobookbay-downloader:
    image: ghcr.io/jamesry96/audiobookbay-automated:latest
    ports:
      - "5078:5078"
    container_name: audiobookbay-downloader
    environment:
      - DOWNLOAD_CLIENT=qbittorrent
      - DL_SCHEME=http
      - DL_HOST=192.168.1.123
      - DL_PORT=8080
      - DL_USERNAME=admin
      - DL_PASSWORD=pass
      - DL_CATEGORY=abb-downloader
      - SAVE_PATH_BASE=/audiobooks
      - ABB_HOSTNAME='audiobookbay.is' #Default
      - NAV_LINK_NAME=Open Audiobook Player #Optional
      - NAV_LINK_URL=https://audiobooks.yourdomain.com/ #Optional
