version: '3.8'

services:
  audiobookbay-downloader:
    image: ghcr.io/jamesry96/audiobookbay-automated:latest
    ports:
      - "5078:5078"
    container_name: audiobookbay-downloader
    environment:
      - DOWNLOAD_CLIENT=qbittorrent
      - DL_SCHEME=http
      - DL_HOST=192.168.31.149
      - DL_PORT=8094
      - DL_USERNAME=admin
      - DL_PASSWORD=adminadmin
      - DL_CATEGORY=abb-downloader
      - SAVE_PATH_BASE=${APP_DATA_DIR}/
